language: node_js

sudo: required

addons:
  code_climate:
    repo_token: 22147b555888e669626dc0aa958203e9ef8ea31e64e3daeed7358a4a33682fd0

node_js:
  - "node"

services:
  - postgresql

before_script:
  - psql -c 'create database mydiary;' -U postgres

install:
  - npm install

cache:
  directories:
    - "node_modules"

after_success:
  - npm run cover

after_script: 
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info

script: npm run test
